name: Bench MLKEM
description: Run benchmarks for MLKEM implementation

runs:
  using: composite
  steps:
        - uses: cachix/install-nix-action@v31
          with:
            nix_path: nixpkgs=channel:nixos-unstable              
        - name: Checks Dependencies
          shell: bash
          run: nix-shell --arg full false --run "echo Dependencies OK…"
        - name : Run Benchmarks
          shell: bash
          run: nix-shell --arg full false --run "make -C bench run"
        - name: Generate Benchmark Summary
          shell: bash 
          run: |
            echo "## Benchmark Results" >> $GITHUB_STEP_SUMMARY
            echo '| **Implementation** | **KeyPair Cycles** | **Enc Cycles** | **Dec Cycles** |' >> $GITHUB_STEP_SUMMARY
            echo '| ----- | ----- | ------ | ------ |' >> $GITHUB_STEP_SUMMARY
            for f in bench/bin/*.out; do
              DATA=$(cat $f)
              echo "| **${f}** ${DATA}" >> $GITHUB_STEP_SUMMARY
            done  