#all : jindcpa.ec jkem.ec

#jindcpa.ec : ../indcpa.jinc

all : 
	jasminc ../jkem.jazz -oec jkem.ec -ec jade_kem_kyber_kyber768_amd64_ref_keypair -ec jade_kem_kyber_kyber768_amd64_ref_enc -ec jade_kem_kyber_kyber768_amd64_ref_dec

clean:
	rm *.ec 