#define CRYPTO_SECRETKEYBYTES  2400
#define CRYPTO_PUBLICKEYBYTES  1184
#define CRYPTO_CIPHERTEXTBYTES 1088
#define CRYPTO_BYTES           32

#define crypto_kem_kyber768_libjade_ravx2_constbranchindex_keypair jade_kem_kyber_kyber768_amd64_avx2_keypair
#define crypto_kem_kyber768_libjade_ravx2_constbranchindex_enc jade_kem_kyber_kyber768_amd64_avx2_enc
#define crypto_kem_kyber768_libjade_ravx2_constbranchindex_dec jade_kem_kyber_kyber768_amd64_avx2_dec
